SWAPI/Models/APIModels/PeopleResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SWAPI.Models.APIModels
{
    public class PeopleResponseModel
    {    
            public string name { get; set; }
            public string height { get; set; }
            public string mass { get; set; }
            public string hair_color { get; set; }
            public string skin_color { get; set; }
            public string eye_color { get; set; }
            public string birth_year { get; set; }
            public string gender { get; set; }
            public string homeworld { get; set; }
            public string[] films { get; set; }
            public object[] species { get; set; }
            public string[] vehicles { get; set; }
            public string[] starships { get; set; }
            public DateTime created { get; set; }
            public DateTime edited { get; set; }
            public string url { get; set; }


    }
}

SWAPI/Models/APIModels/PlanetResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SWAPI.Models.APIModels
{
    public class PlanetResponseModel
    {      
            public string name { get; set; }
            public string rotation_period { get; set; }
            public string orbital_period { get; set; }
            public string diameter { get; set; }
            public string climate { get; set; }
            public string gravity { get; set; }
            public string terrain { get; set; }
            public string surface_water { get; set; }
            public string population { get; set; }
            public object[] residents { get; set; }
            public string[] films { get; set; }
            public DateTime created { get; set; }
            public DateTime edited { get; set; }
            public string url { get; set; }
        

    }
}

SWAPI/Models/ErrorViewModel.cs
using System;

namespace SWAPI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SWAPI/Models/ViewModels/GetPersonByIdViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SWAPI.Models.ViewModels
{
    public class GetPersonByIdViewModel
    {
        public string name { get; set; }
        public string birth_year { get; set; }
        public string gender { get; set; }


    }
}

SWAPI/Models/ViewModels/GetPlanetByIdViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SWAPI.Models.ViewModels
{
    public class GetPlanetByIdViewModel
    {
        public string name { get; set; }
        public string rotation_period { get; set; }
        public string orbital_period { get; set; }
        public string climate { get; set; }
        public string gravity { get; set; }
        public string terrain { get; set; }
    }
}

SWAPI/Models/ViewModels/PlanetOrPersonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SWAPI.Models.ViewModels
{
    public class PlanetOrPersonViewModel
    {
        public string PeopleId { get; set; }

        public string PlanetId { get; set; }
    }
}

SWAPI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SWAPI.Models;

namespace SWAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SWAPI/Controllers/StarWarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SWAPI.Models.ViewModels;

namespace SWAPI.Controllers
{
    public class StarWarsController : Controller
    {
        private readonly StarWarsClient _starWarsClient;

        public StarWarsController(StarWarsClient starWarsClient)
        {
            _starWarsClient = starWarsClient;
        }

        public IActionResult PlanetOrPerson()
        {
            return View();
        }

        public async Task<IActionResult> GetPersonById(PlanetOrPersonViewModel model)
        {

            var response = await _starWarsClient.GetSinglePerson(model.PeopleId);

            var viewModel = new GetPersonByIdViewModel
            {
                name = response.name,
                gender = response.gender,
                birth_year = response.birth_year,                
            };


            return View(viewModel);
        }

        public async Task<IActionResult> GetPlanetById(PlanetOrPersonViewModel model)
        {

            var response = await _starWarsClient.GetSinglePlanet(model.PlanetId);

            var viewModel = new GetPlanetByIdViewModel
            {
                name = response.name,
                rotation_period = response.rotation_period,
                orbital_period = response.orbital_period,
                climate = response.climate,
                gravity = response.gravity,
                terrain = response.terrain
            };

            return View(viewModel);
        }


    }
}

SWAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SWAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SWAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SWAPI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StarWars" asp-action="PlanetOrPerson">Choose Planet or Person</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SWAPI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SWAPI/Views/StarWars/GetPersonById.cshtml
@{
    ViewData["Title"] = "GetPersonById";
}

@model SWAPI.Models.ViewModels.GetPersonByIdViewModel


    <div class="container">
        <h1>Name: @Model.name</h1>
        <h1>Birth Year: @Model.birth_year</h1>
        <h1>Gender: @Model.gender</h1>
    


    </div>

SWAPI/Views/StarWars/GetPlanetById.cshtml
@{
    ViewData["Title"] = "GetPlanetById";
}

@model SWAPI.Models.ViewModels.GetPlanetByIdViewModel


    <div class="container">
        <h1>Name: @Model.name</h1>
        <h1>Rotation Period: @Model.rotation_period</h1>
        <h1>Orbital Period: @Model.orbital_period</h1>
        <h1>Climate: @Model.climate</h1>
        <h1>Gravity: @Model.gravity</h1>
        <h1>Terrain: @Model.terrain</h1>


    </div>

SWAPI/Views/StarWars/PlanetOrPerson.cshtml
@{
    ViewData["Title"] = "PlanetOrPerson";
}

@model SWAPI.Models.ViewModels.PlanetOrPersonViewModel  


    <form asp-controller="StarWars" asp-action="GetPersonById" method="post">

        <label>Input Person ID</label>
        <input asp-for="PeopleId" />


        <button>Search For Person</button>

    </form>

<br />
<br />
<br />
<br />
<form asp-controller="StarWars" asp-action="GetPlanetById" method="post">

    <label>Input Planet ID</label>
    <input asp-for="PlanetId" />

    <button>Search For Planet</button>

</form>